# Natural Fibre Composite Machine Learning Project

## Project Objective

The objective of this project is to develop machine learning models to predict
the mechanical properties of natural fibre composites.

The target properties are:

- Tensile Strength (MPa)
- Elastic Modulus (MPa)

The project uses supervised machine learning regression techniques to understand
how material characteristics influence composite performance.

In [1]:
import pandas as pd
import numpy as np

## Dataset Loading

The dataset is loaded in its original form.
No cleaning or modifications are performed at this stage.
The purpose is only to understand the structure and quality of the data.

In [3]:
# Load dataset

df = pd.read_csv("../data/raw/natural_fibre_composites.csv")

# Display first five rows

df.head()

,fiber_type,matrix_type,fiber_configuration,orientation,num_plies,fiber_volume_fraction,elastic_modulus_mpa,tensile_strength_mpa,data_source
0,Flax,Epoxy,0,0 UD,3.0,0.3,20042.2367,297.4065,"Torres et al. (2017), Data in Brief, Vol.12, p..."
1,Flax,Epoxy,0,0 UD,3.0,0.3,19701.1091,289.9346,"Torres et al. (2017), Data in Brief, Vol.12, p..."
2,Flax,Epoxy,0,0 UD,3.0,0.3,17559.1106,274.8862,"Torres et al. (2017), Data in Brief, Vol.12, p..."
3,Flax,Epoxy,0,0 UD,3.0,0.3,19737.9379,277.5509,"Torres et al. (2017), Data in Brief, Vol.12, p..."
4,Flax,Epoxy,0,0 UD,3.0,0.3,18048.3804,286.1064,"Torres et al. (2017), Data in Brief, Vol.12, p..."

## Dataset Dimensions

This section identifies the number of samples and features available.

In [4]:
# Number of rows and columns

df.shape

(3083, 9)

In [5]:
print("Number of samples:", df.shape[0])
print("Number of features:", df.shape[1])

Number of samples: 3083
Number of features: 9

## Dataset Features

The dataset contains different material and manufacturing characteristics.

In [6]:
# Display column names

df.columns

Index(['fiber_type', 'matrix_type', 'fiber_configuration', 'orientation',
       'num_plies', 'fiber_volume_fraction', 'elastic_modulus_mpa',
       'tensile_strength_mpa', 'data_source'],
      dtype='str')

## Dataset Information

This section identifies:

- Column names
- Data types
- Missing values

In [7]:
# Dataset Information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3083 entries, 0 to 3082
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fiber_type             3083 non-null   str
 1   matrix_type            3071 non-null   str
 2   fiber_configuration    3083 non-null   str
 3   orientation            3083 non-null   str
 4   num_plies              3040 non-null   float64
 5   fiber_volume_fraction  3059 non-null   float64
 6   elastic_modulus_mpa    598 non-null    float64
 7   tensile_strength_mpa   3083 non-null   float64
 8   data_source            3083 non-null   str
dtypes: float64(4), str(5)
memory usage: 216.9 KB

In [8]:
# First Five Rows

df.head()

,fiber_type,matrix_type,fiber_configuration,orientation,num_plies,fiber_volume_fraction,elastic_modulus_mpa,tensile_strength_mpa,data_source
0,Flax,Epoxy,0,0 UD,3.0,0.3,20042.2367,297.4065,"Torres et al. (2017), Data in Brief, Vol.12, p..."
1,Flax,Epoxy,0,0 UD,3.0,0.3,19701.1091,289.9346,"Torres et al. (2017), Data in Brief, Vol.12, p..."
2,Flax,Epoxy,0,0 UD,3.0,0.3,17559.1106,274.8862,"Torres et al. (2017), Data in Brief, Vol.12, p..."
3,Flax,Epoxy,0,0 UD,3.0,0.3,19737.9379,277.5509,"Torres et al. (2017), Data in Brief, Vol.12, p..."
4,Flax,Epoxy,0,0 UD,3.0,0.3,18048.3804,286.1064,"Torres et al. (2017), Data in Brief, Vol.12, p..."

In [9]:
# Last Five Rowss

df.tail()

,fiber_type,matrix_type,fiber_configuration,orientation,num_plies,fiber_volume_fraction,elastic_modulus_mpa,tensile_strength_mpa,data_source
3078,Jute / Sisal Scaffold,Epoxy,Sandwich,Woven,NaN,NaN,6351.0,147.0,Balamurugan (2022)
3079,Jute / Sisal Scaffold,Epoxy,Sandwich,Woven,NaN,NaN,NaN,136.0,Balamurugan (2022)
3080,Jute / Sisal Scaffold,Epoxy,Sandwich,Woven,NaN,NaN,6656.0,138.0,Balamurugan (2022)
3081,Jute / Sisal Scaffold,Epoxy,Sandwich,Woven,NaN,NaN,NaN,121.0,Balamurugan (2022)
3082,Jute / Sisal Scaffold,Epoxy,Sandwich,Woven,NaN,NaN,NaN,132.0,Balamurugan (2022)

## Data Type Analysis

Machine learning requires understanding which variables are numerical
and which variables are categorical.

In [10]:
# Display data types

df.dtypes

fiber_type                   str
matrix_type                  str
fiber_configuration          str
orientation                  str
num_plies                float64
fiber_volume_fraction    float64
elastic_modulus_mpa      float64
tensile_strength_mpa     float64
data_source                  str
dtype: object

In [11]:
# Numerical Features

numerical_features = df.select_dtypes(include=np.number).columns

numerical_features

Index(['num_plies', 'fiber_volume_fraction', 'elastic_modulus_mpa',
       'tensile_strength_mpa'],
      dtype='str')

In [12]:
# Categorical Features

categorical_features = df.select_dtypes(include='str').columns

categorical_features

Index(['fiber_type', 'matrix_type', 'fiber_configuration', 'orientation',
       'data_source'],
      dtype='str')

## Missing Value Analysis

Missing values are identified but not treated at this stage.
Cleaning decisions will be made in the next notebook.

In [13]:
# Count missing values

missing_values = df.isnull().sum()

missing_values

fiber_type                  0
matrix_type                12
fiber_configuration         0
orientation                 0
num_plies                  43
fiber_volume_fraction      24
elastic_modulus_mpa      2485
tensile_strength_mpa        0
data_source                 0
dtype: int64

In [14]:
# Percentage missing

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

fiber_type                0.000000
matrix_type               0.389231
fiber_configuration       0.000000
orientation               0.000000
num_plies                 1.394745
fiber_volume_fraction     0.778463
elastic_modulus_mpa      80.603308
tensile_strength_mpa      0.000000
data_source               0.000000
dtype: float64

## Duplicate Analysis

Duplicate records are checked to understand whether repeated observations exist.

In [15]:
# Count duplicate rows

df.duplicated().sum()

np.int64(0)

## Statistical Summary

This section provides descriptive statistics for numerical variables.

In [16]:
# Summary statistics

df.describe()

,num_plies,fiber_volume_fraction,elastic_modulus_mpa,tensile_strength_mpa
count,3040.000000,3059.000000,598.000000,3083.000000
mean,12.889803,0.488934,7808.709773,1117.482963
std,6.653955,0.118379,4223.035009,589.328770
min,1.000000,0.000000,43.900000,0.086000
25%,7.000000,0.400000,5794.517875,901.400000
50%,13.000000,0.480000,6745.621700,1242.200000
75%,19.000000,0.590000,8594.010450,1508.500000
max,24.000000,0.700000,20551.130300,2718.000000

## Unique Values in Categorical Variables

This section examines the different categories present in the dataset.

In [17]:
# Number of unique values in each column

df.nunique()

fiber_type                 24
matrix_type                10
fiber_configuration        14
orientation                12
num_plies                  23
fiber_volume_fraction      48
elastic_modulus_mpa       586
tensile_strength_mpa     2841
data_source                27
dtype: int64

# Initial Dataset Observations

From the initial inspection, the dataset contains information about natural
fibre composite materials and their mechanical properties.

The dataset includes numerical and categorical variables describing material
composition and manufacturing conditions.

Missing values, duplicate records, and variable distributions have been
identified. These issues will be addressed during the data cleaning and
exploratory data analysis stage.